### ISSUE TITLE
Interaction get's disabled after appDelegate.startUnity()

### ISSUE THREAD

**Issue by dbambulaks** [jiulongw/swift-unity#86] opened 2018-06-18 11:12 UTC
Hey, I've finally got everything built, and Unity player actually starts. But for the some reason, all the buttons gets disabled in the navigation controller. Any ideas what could be wrong?

It happens after calling startUnity() the first time in AppDelegate. I've tried to do the first call from ViewController as well - got the same problem.
    
Either Unity somehow overlays the navigation controller (but i don't think so, since I've checked it in View Hierarchy), or there are some others errors causing such behaviour...

**Comment by PrashantKT** [comment] 2018-06-18 11:15
See this 
 https://stackoverflow.com/questions/50403987/integrating-unityvuforia-to-existing-ios-project-make-user-interaction-not-work/50595308#50595308

**Comment by quotetoxic** [comment] 2018-06-18 12:46
I don't have any additional services in appDelegate... But now Vuforia wants to start, but it throws:
 
Screen position out of view frustum (screen pos 0.000000, 0.000000, 2000.000000) (Camera rect 0 0 0 0)
System.IComparable`1:CompareTo(T)
System.IComparable`1:CompareTo(T)
System.IComparable`1:CompareTo(T)

[ line 3257] 
(Filename:  Line: 3257)

OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is not complete or incompatible with command
UnityEngine.GL:GLIssuePluginEvent(IntPtr, Int32)
UnityEngine.GL:IssuePluginEvent(IntPtr, Int32)
Vuforia.VuforiaRenderer:UnityRenderEvent(RenderEvent)
Vuforia.VuforiaManager:FinishRendering()
Vuforia.VideoBackgroundBehaviour:OnPostRender()
System.IComparable`1:CompareTo(T)
System.IComparable`1:CompareTo(T)
System.IComparable`1:CompareTo(T)

[/Users/builduser/buildslave/unity/build/Runtime/GfxDevice/opengles/GfxDeviceGLES.cpp line 336] 
(Filename: /Users/builduser/buildslave/unity/build/Runtime/GfxDevice/opengles/GfxDeviceGLES.cpp Line: 336)

**Comment by PrashantKT** [comment] 2018-06-18 13:05
Remove the constraints  unlike demo, Try to add unity view with setFrame

**Comment by maiido** [comment] 2018-09-12 16:51
Same issue with unity 2018.2.7f1, vuforia 7.2.24 and iOS 11.4.1. We don't have any additional services in appDelegate. In fact we also try to move the start and stop and the issue is the same. It appears after we call stopUnity. it's like Unity keeps receiving events.

**Comment by maiido** [comment] 2018-09-14 06:00
we've been doing it all over again (the Unity part) to see where it blocks but no issue with the touch. Very Strange...

**Comment by tdd32** [comment] 2018-09-26 08:17
We had a similar problem. Our Unity/Vuforia app needed to be opened in fullscreen and landscape left (like it was configured inside Unity) because embedding it inside a `UIContainerView` or anything else resulted in a white screen (but debug console was showing normal startup). After stopping Unity we did come to the same behaviour, where inside our Swift application no button was clickable anymore.
After some try&error and googling we discovered that with `currentUnityController.application(application, didFinishLaunchingWithOptions: launchOptions)` a new `UIWindow` ist created, holding the Unity controller and view. With `startUnity()` the `UIWindow` does become the `KeyWindow` for the application, meaning it will receive all touchevents. After we succeeded in switching back to our Swift app part and stopping Unity, we found out that the `UIWindow` from Unity was still being considered `KeyWindow`. So long story short, our solution now is to do some "window handling" our self and call `makeKeyAndVisible()` on our Swift window to get it to receive touchevents again.

**Comment by mbogh** [comment] 2018-10-02 13:22
@tdd32 I just got a new Unity export and even if I do `makeKeyAndVisible()` after the Unity dance it still sits as the key window.

```swift
#if UNITY
        unity_init(CommandLine.argc, CommandLine.unsafeArgv)

        currentUnityController = UnityAppController()
        currentUnityController.application(application, didFinishLaunchingWithOptions: launchOptions)

        startUnity()
        stopUnity()
        #endif

        if window.rootViewController == nil {
            window.rootViewController = StartupLoadingViewController()
        }
        window.makeKeyAndVisible()
```

**Comment by Astoration** [comment] 2019-07-08 02:11
I think this is a problem for UIWindow.
In fact, check out the Hierarchy Debugger and you can see that there are two UIWindows.
Typically, an application uses one UIWindow, but creates a UIWindow during initialization in UnityEngine.
I think there may be another UIWindow blocking another UIWindow.
The `setWindowLevel` method can be resolved by adjusting the order of the UIWindow as follows.
```objc
#import "Unity/Classes/Unity/DisplayManager.h"
- (void) startUnity{
    if(!self.isUnityRunning){
        [self setIsUnityRunning:YES];
        [_currentUnityController applicationDidBecomeActive:_application];
        [[[[DisplayManager Instance] mainDisplay] window] setWindowLevel:0];
    }
}

- (void) stopUnity{
    if(self.isUnityRunning){
        [_currentUnityController applicationWillResignActive:_application];
        [[[[DisplayManager Instance] mainDisplay] window] setWindowLevel:-1];
        [self setIsUnityRunning:NO];
        AppDelegate* appDelegate = [[UIApplication sharedApplication] delegate];
        [[appDelegate window] makeKeyAndVisible];
    }
}
```

**Closed** 2023-09-25 05:34 UTC
