### ISSUE TITLE
ARKit classes build error

### ISSUE THREAD

**Issue by bilalpakeermohamed** [jiulongw/swift-unity#45] opened 2018-02-21 16:57 UTC
Hi @jiulongw. Thanks for the great solution for the swift-unity interface!

I tried adding the ARKit plugin to the demo project and built it to check whether I can use the ARKit features in the final app. I am getting the following error,

![screen shot 2018-02-21 at 16 53 58](https://user-images.githubusercontent.com/19821714/36493602-e4ad6440-1727-11e8-9531-f072ee94bb36.png)

The error is on the ARSessionNative.mm file which is imported into Unity by the ARKit plugin. Will appreciate it, if you could have a look :)

**Comment by jiulongw** [comment] 2018-02-21 17:40
You can always compare project settings with a working Xcode application to see what's missing :)

In your case, it seems like `ARKIT_USE_FACETRACKING` needs to be defined for ARKIT to work properly.  Try to add `-DARKIT_USE_FACETRACKING` in `OTHER_CFLAGS` in [Unity.xcconfig](https://github.com/jiulongw/swift-unity/blob/master/demo/xcode/DemoApp/Unity/Unity.xcconfig#L11)

**Comment by bilalpakeermohamed** [comment] 2018-02-22 17:04
Hi jiulongw. Thanks for the reply. 

I tried adding -ARKIT_USE_FACETRACKING in OTHER_CFLAGS but I am getting the same error. I tried it with different comibinations, -ARKIT_USE_FACETRACKING, -ARKIT_USE_FACETRACKING = 1, -ARKIT_USE_FACETRACKING = 0 etc., but I am not able to build the code.

Could you please let me know what is wrong. Please find attached the screenshot of the Unity.xcconfig file.
![screen shot 2018-02-22 at 17 02 07](https://user-images.githubusercontent.com/19821714/36552720-78de7d28-17f2-11e8-8fac-981698f9516b.png)

**Comment by jiulongw** [comment] 2018-02-22 17:43
Ah, I misspelled the word.  Look careful on the #if statement in your code, it is `ARKIT_USES_FACETRACKING` not `ARKIT_USE_FACETRACKING`...  Try that and it should work.

**Comment by jiulongw** [comment] 2018-02-23 04:45
Closing this issue since I believe it is the root cause.  Feel free to re-open if you still have issue.

**Closed by jiulongw** 2018-02-23 04:45 UTC

**Comment by bilalpakeermohamed** [comment] 2018-02-23 16:48
Hi jiulongw. Yes, the typo was the issue for the error that I was having. I am still unable to use the ARKit plugin in the project as I am running into more errors. 

If you don't mind could you please import the ARKit plugin into your Unity project and let me know the setps that you do to build the XCode project.

Sorry, it is because I am a Unity dev and my experience with XCode and Swift is pretty bad. Will appreciate it. Happy to help you out if you have any Unity or 3D modeling issues in the future :)

**Comment by bilalpakeermohamed** [comment] 2018-02-26 12:21
Hi jiulongw. I am running into the following error after adding -ARKIT_USES_FACETRACKING =1. Could you please let me know what the issue is? 

![screen shot 2018-02-26 at 12 14 03](https://user-images.githubusercontent.com/19821714/36670144-33f5838c-1aef-11e8-8499-58b47ef9deca.png)

**Comment by jiulongw** [comment] 2018-02-26 17:50
`-DARKIT_USES_FACETRACKING=1`, prefix with `-D`
