### ISSUE TITLE
ld: entry point (_main) undefined. for architecture arm64

### ISSUE THREAD

**Issue by ElectricSquare-DinoDini** [jiulongw/swift-unity#30] opened 2017-12-20 14:27 UTC
Hi,

I am trying to use this and have built from a clean project. Once the postbuild step is included, the build fails with 

ld: entry point (_main) undefined. for architecture arm64

I compared the log of the successful build vs. the failed build (that is one without the post build step and one with) and the only difference in the logs is the order of two pngs and two source files.

I would appreciate any ideas, cheers...

-DD

**Comment by jiulongw** [comment] 2017-12-20 17:35
This is by design. The Unity output (after applying the post build script) is not meant to be built by Xcode directly (that's why it's recommended to be dropped to /tmp). Instead, you should open the companion Swift Xcode project, which will copy the necessary files from Unity output and build the iOS app.

**Comment by jiulongw** [comment] 2017-12-22 19:26
Closed as dup with #17

**Closed by jiulongw** 2017-12-22 19:26 UTC
